#!/bin/bash

cd $(dirname $(readlink -f $0))

emoji=$(
    jq -r '.[] | .name, .code_points.base' emojione.json |\
    while read name && read codepoint; do
        printf "\\U$codepoint $name\n"
    done |\
    dmenu |\
    awk '{print $1}')
xdotool type "$emoji"
